/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClassManagementForm;

import ClassManagement.AddNotOpenClassEdited;
import ClassManagement.AddOpenClass;
import ClassManagement.NotOpenedClassEdit;
import ClassManagement.OpenedClassEdit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author YOU
 */
public class NotOpendClassEditForm extends javax.swing.JFrame {

    /**
     * Creates new form NotOpendClassEdit
     */
    public NotOpendClassEditForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1_back1 = new javax.swing.JButton();
        jTextField_ClassNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_ClassName = new javax.swing.JTextField();
        jTextField_ChdMajor = new javax.swing.JTextField();
        jTextField_Pnt = new javax.swing.JTextField();
        jButton1_Find = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("강좌번호");

        jButton1_back1.setText("뒤로가기");
        jButton1_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_back1ActionPerformed(evt);
            }
        });

        jLabel2.setText("수업담당자 - 개설되지 않은 강좌 수정");

        jLabel4.setText("강좌이름");

        jLabel5.setText("담당학과");

        jLabel6.setText("학점");

        jTextField_Pnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PntActionPerformed(evt);
            }
        });

        jButton1_Find.setText("찾기");
        jButton1_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_FindActionPerformed(evt);
            }
        });

        jButton2.setText("수정");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_Delete.setText("삭제");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1_back1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_ClassNum, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_ChdMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Pnt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_ClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Delete)
                    .addComponent(jButton2)
                    .addComponent(jButton1_Find))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1_back1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_ClassNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_Find))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ChdMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Pnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Delete)
                        .addGap(25, 25, 25)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_back1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1_back1ActionPerformed

    private void jTextField_PntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PntActionPerformed

    private void jButton1_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_FindActionPerformed
        // 개설되지 않은 강좌 수정에서 검색버튼에 대한 기능 
        String ClassNum = jTextField_ClassNum.getText();
        // 검색할 강좌 번호를 입력한 텍스트 필드의 내용을 받을 String 변수 
        OpenedClassEdit OpnClassEdit = new OpenedClassEdit(); // 개설된 강좌 텍스트 파일에 접근하는 클래스 선언 
        OpnClassEdit.Find(); // 개설된 강좌 텍스트 파일을 줄 단위로 읽고 ArrayList에 저장하는 메소드 선언 
        OpnClassEdit.SplitLine(ClassNum); // 검색할 강좌의 번호가 포함된 줄을 가지고 공백 단위로 스플릿해서 배열에 저장
        
        NotOpenedClassEdit NopClassEdit = new NotOpenedClassEdit(); // 등록된 강좌 텍스트 파일에 접근하는 클래스 선언
        NopClassEdit.Find(); //등록된 강좌 텍스트 파일을 줄 단위로 읽고 ArrayList에 저장하는 메소드 선언 
        NopClassEdit.SplitLine(ClassNum); // 검색할 강좌의 번호가 포함된 줄을 가지고 공백 단위로 스플릿해서 배열에 저장

        if (ClassNum.equals( OpnClassEdit.SPline0()) == true){
        // 강좌번호 텍스트 필드에 입력된 값이 개설된 강좌 텍스트 파일에 있다면 수정하지 못한다. 
        //그래서 개설된 강좌입니다 메시지 박스를 출력 후 강좌번호를 제외한 나머지 텍스트 필드들을 null로 초기화
            JOptionPane aaa;
            aaa = new JOptionPane();
            JOptionPane.showMessageDialog(null, "개설된 강좌입니다.");
            
            jTextField_ClassName.setText(null);
            jTextField_ChdMajor.setText(null);
            jTextField_Pnt.setText(null);
        }

        else if(ClassNum.equals( NopClassEdit.SPline0())){
        // 강좌번호 텍스트 필드에 입력된 값이 개설되지 않은 텍스트 파일에 있다면 수정이 가능하다. 
        // 그래서 스플릿을 이용해 입력된 값이 있는 줄을 스플릿을 사용하여 각각 쪼갠 후 강좌번호, 강좌이름, 담당학과, 학점 순으로 출력한다.
            jTextField_ClassNum.setText(NopClassEdit.SPline0());
            jTextField_ClassName.setText(NopClassEdit.SPline1());
            jTextField_ChdMajor.setText(NopClassEdit.SPline2());
            jTextField_Pnt.setText(NopClassEdit.SPline3());
        }

        else{
        // 두 텍스트 파일 어디에도 없다면 정보가 없다는 메시지 박스를 출력한다. 
            JOptionPane aaa;
            aaa = new JOptionPane();
            JOptionPane.showMessageDialog(null, "정보가 없습니다.");
              
            jTextField_ClassName.setText(null);
            jTextField_ChdMajor.setText(null);
            jTextField_Pnt.setText(null);
        }
        
    }//GEN-LAST:event_jButton1_FindActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 개설되지 않은 강좌에 대해 수정하는 기능
        String ClassNum =  jTextField_ClassNum.getText();
        String ClassName = jTextField_ClassName.getText();
        String ChdMajor = jTextField_ChdMajor.getText();
        String Point = jTextField_Pnt.getText();
        // 강좌번호, 강좌이름, 담당학과, 학점 텍스트 필드들을 받을 스트링 변수 각각 선언
        NotOpenedClassEdit NopClassEdit = new NotOpenedClassEdit();  // 등록된 강좌 텍스트 파일에 접근하는 클래스 선언
        NopClassEdit.Find(); //등록된 강좌 텍스트 파일을 줄 단위로 읽고 ArrayList에 저장하는 메소드 선언 
        NopClassEdit.SplitLine(ClassNum); // 검색할 강좌의 번호가 포함된 줄을 가지고 공백 단위로 스플릿해서 배열에 저장
                
        String EditForm = NopClassEdit.SPline0() + " " + ClassName + " " + ChdMajor + " " + Point;
        // 등록된 강좌 텍스트 파일에 변경할 내용을 담는 스트링 변수 선언 
        try {
            NopClassEdit.FindLine(ClassNum); // 검색한 강좌번호 텍스트 필드에 입력된 강좌번호를 텍스트 파일에서 지운다.
        } catch (IOException ex) {
            Logger.getLogger(OpenedClassEditForm.class.getName()).log(Level.SEVERE, null, ex);
        }//해당 라인의 수업 지우기
        
        AddNotOpenClassEdited NAoc = new AddNotOpenClassEdited(); // 등록된 강좌 텍스트 파일에 접근하는 클래스 선언 
        try {
            NAoc.Add(EditForm); // 변경할 내용을 담는 스트링 변수를 추가하는 Add메소드 사용 
             
            JOptionPane aaa;
            aaa = new JOptionPane();
            JOptionPane.showMessageDialog(null, "수정 성공");
            // 수정 성공 메시지 박스를 출력한다.
        } catch (IOException ex) {
            Logger.getLogger(OpenedClassEditForm.class.getName()).log(Level.SEVERE, null, ex);
        } // 지운 라인에 수업 항목 다시 추가
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
      //입력된 강좌에 대한 내용을 모두 지우는 기능 
        String ClassNum =  jTextField_ClassNum.getText();
        
        NotOpenedClassEdit NopClassEdit = new NotOpenedClassEdit();  // 등록된 강좌 텍스트 파일에 접근하는 클래스 선언
        NopClassEdit.Find(); //등록된 강좌 텍스트 파일을 줄 단위로 읽고 ArrayList에 저장하는 메소드 선언 
        NopClassEdit.SplitLine(ClassNum); // 검색할 강좌의 번호가 포함된 줄을 가지고 공백 단위로 스플릿해서 배열에 저장
        
           try {
            NopClassEdit.FindLine(ClassNum); // 검색한 강좌번호 텍스트 필드에 입력된 강좌번호를 텍스트 파일에서 지운다.
        } catch (IOException ex) {
            Logger.getLogger(OpenedClassEditForm.class.getName()).log(Level.SEVERE, null, ex);
        }//해당 라인의 수업 지우기
          
           JOptionPane aaa;
            aaa = new JOptionPane();
            JOptionPane.showMessageDialog(null, "삭제 성공");
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotOpendClassEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotOpendClassEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotOpendClassEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotOpendClassEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotOpendClassEditForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_Find;
    private javax.swing.JButton jButton1_back1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField_ChdMajor;
    private javax.swing.JTextField jTextField_ClassName;
    private javax.swing.JTextField jTextField_ClassNum;
    private javax.swing.JTextField jTextField_Pnt;
    // End of variables declaration//GEN-END:variables
}
